// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
 #include "./SimplexNoise.compute"

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!


    float n = ClassicNoise2D(id.xy / 37.23f);

    Result[id.xy] = float4(n, n, n, 1);
}
